
## minio配置
minio:
  url: http://192.168.123.14:8000
  access-key: atEunTajNwLBzvmt
  secret-key: NyDAdZsJVGWc0Cab3fFK42jFwD1yW9Vr
  bucket-name: chat-ai-bucket

libreoffice:
  home:
    linux: /usr/lib64/libreoffice