
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  application:
    name: split-file

server:
  port: 8086
  servlet:
    context-path: /split-file