
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  application:
    name: split-file
  profiles:
    active: '@package.environment@'

server:
  port: 8088
  servlet:
    context-path: /split-file

logging:
  level:
    org:
      jodconverter: debug