
## minio配置
minio:
  url: https://filestore.unisoc.com
  access-key: atEunTajNwLBzvmt
  secret-key: NyDAdZsJVGWc0Cab3fFK42jFwD1yW9Vr
  bucket-name: chat-ai-bucket

libreoffice:
  home:
    linux: /usr/lib/libreoffice